# Centralized locator repository
# Format: key=type>locator
# Types: id, name, css, xpath, class, tag

login.email=name>email
login.password=name>password
login.button=xpath>//button[normalize-space()='Sign in']
login.emailError=xpath>//p[@id='_R_ainebn9esndlb_-form-item-message']
login.passwordError=xpath>//p[@id='_R_einebn9esndlb_-form-item-message']
login.logout=id>logout
